/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPasswordInput: typeof import('vant/es')['PasswordInput']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanActionSheet: typeof import('vant/es')['ActionSheet']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanDialog: typeof import('vant/es')['Dialog']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
  const VanForm: typeof import('vant/es')['Form']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanLoading: typeof import('vant/es')['Loading']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
  const VanPasswordInput: typeof import('vant/es')['PasswordInput']
  const VanPicker: typeof import('vant/es')['Picker']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanStep: typeof import('vant/es')['Step']
  const VanSteps: typeof import('vant/es')['Steps']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabs: typeof import('vant/es')['Tabs']
  const VanTag: typeof import('vant/es')['Tag']
  const VanUploader: typeof import('vant/es')['Uploader']
}